name: simple_gql
description: A minimal library to do GQL queries and mutations (subscriptions comming soon)
version: 1.0.0
homepage: https://github.com/lecuivre-alban/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
